                   
                     seyhakupdate
កម្រងស្នេហ៍ខ្ញុំ💞
🖋️កាលពីដំបូងខ្ញុំបានស្គាល់គាត់តាមរយ:ហ្វេសប៊ុក មានថ្ងៃមួយមួយនោះ
ខ្ញុំបានឃើញគាត់ផុសរៀបរាប់ជាពាក្សស្លោកអប់រំចិត្តមួយឃ្លា
ពេលនោះខ្ញុំបានអានចប់ហើយយកមកពិចារណាឃើញថាត្រឹត្រូវ
ខ្ញុំមានអារម្មណ៍ថាពេញចិត្តនឹងទស្សនៈរបស់គាត់ណាស់
ហើយខ្ញុំតាមមើលគ្រប់កាផុសនឹងតាមឡាយរបស់គាត់
ខ្ញុំមិនបានដឹងថាគាត់គឺជាមនុស្សស្រីទេស្មានតែជាមនុស្សប្រុសទេ
រហូតដល់ថ្ងៃមួយខ្ញុំបានឃើញ គាត់ផុសពាក្យពេចន៍មានមួយឃ្លាទៀត
ហើយបានភ្ជាប់មកជាមួយនូវរូបថតមួយសន្លឹក របស់គាត់ផ្ទាល់ដ៏ស្រស់ស្អាត💓
ពេលនោះហើយ... ពេលនោះហើយ... ដែលខ្ញុំបានឃើញមុខរបស់គាត់ជាលើកដំបូង ហើយខ្ញុំក៏បានមានចិត្តប្រតិព័ទ្ធលើគាត់ចាប់ពីពេលនោះឯង
បន្ទាប់ពីបានឃើញមុខគាត់ម្ដងមកខ្ញុំមានអារម្មណ៍ថានឹកគាត់ណាស់
រហូតខ្ញុំដាច់ចិត្តឆាតទៅគាត់ហើយសុំរាបអានគាត់ ទាំងអារម្មណ៍ភ័យអរៗ
ពេលគាត់បានឆ្លើយតបថាយល់ព្រមរាប់អានខ្ញុំ ខ្ញុំត្រេកអរណាស់
ហើយពួកយើងបានឆ្លើយឆ្លងគ្នាតាមឆាតរហូតដល់ពេលនោះ
ខ្ញុំបានសារភាពថាស្រលាញ់គាត់ជាលើកដំបូង....
ហើយពេលនោះខ្ញុំបានទទួុល ការបរាជ័យមួយដងទៅពីដង....😭😭😭
ខ្ញុំពិបាកចិត្តខ្លាំងណាស់ តែខ្ញុំមិនបោះបង់ទេខ្ញុំនៅតស៊ូរនឹងព្យាយាមបន្តទៀត💪
យើងបន្តនិយាយគ្នារហូត ហើយពួកយើងនិយាយកាន់តែចុះសំរុងទៅ
ហើយមានចំនុចដូចនឹងស្របគ្នាកាន់តែច្រើនៗទៅ 😀😀😀
ពេលនោះខ្ញុំបានដាច់ចិត្តសារភាពជាលើកទីបីប្រាប់ពីសេចក្ដីស្រលាញ់ម្ដងទៀត
ហើយខ្ញុំបានទទួលនូវចម្លើយមួយដ៏ស្មានមិនដល់....💞💞💞😍😍😍
គឺគាត់ព្រមទទួលក្ដីស្រឡាញ់របស់ខ្ញុំ ពេលនោះខ្ញុំត្រេកអខ្លាំងណាស់
ជីវិតរបស់ខ្ញុំដែលរស់ឱបទុក្ខរៀងរាល់ថ្ងៃ បានប្រែក្លាយទៅជា
ជីវិតថ្មីមួយដ៏ស្រស់បំព្រង រស់ដោយមានក្ដីសង្ឃឹមសាជាថ្មីម្ដងទៀត
ហើយគាត់សុំពេលបញ្ជាក់ពីចិត្្តរបស់ខ្ញុំ ដោយពួកយើងបានសិក្សាពីគ្នាទៅវិញទៅមក...
មានថ្ងៃមួយនោះខ្ញុំបានយករឿងដែលខ្ញុំស្រលាញ់គាត់ ទៅប្រាប់ម្ដាយរបស់ខ្ញុំ
ម្ដាយខ្ញុំគាត់សប្បាយចិត្តហើយព្រម នឹងគិតគូរតាមទំនៀមទំលាប់
អោយពួកយើងថែមទៀតផង ខ្ញុំមានរម្មណ៍រំភើបខ្លាំងណាស់
នឹងបានយកដំណឹងល្អនោះទៅប្រាប់គាត់
នៅមានវគ្គបន្ត🙏✍️📝

 
